### ISSUE TITLE
thread support  compiled in the C++ runtime

### ISSUE THREAD

**Issue by kas1e** [sba1/adtools#12] opened 2016-01-16 08:09 UTC
For building latest verions of Webkit engine (used in Odyssey browser), we need to have the thread support compiled in the C++ runtime. 

For thread support in C++11 on AROS, dedwood use pthread library created by BSzili. OS4 have our own pthreads.library too, but if there can be any problems with, we can use opensource BSzili's pthreads: https://github.com/BSzili/aros-stuff/tree/master/pthreads , as they well tested on morphos/aros.

Here is AROS diff patch which used to build GCC with enalbed chrono, pthreads (with fixes where is need it), so probably that will help a lot to make it all faster:
https://github.com/ezrec/AROS-mirror/blob/ABI_V1/AROS/tools/crosstools/gcc-4.8.3-aros.diff

**Comment by kas1e** [comment] 2016-01-17 07:08
After we deal with Chrono stuff, we meet with c++11 thread support :(

Errors (if it will of any help), looks like this:

```
[  0%] Building CXX object Source/WTF/wtf/CMakeFiles/WTF.dir/CompilationThread.cpp.obj
/amiga/odyssey/OdysseyWebBrowser/Source/WTF/wtf/CompilationThread.cpp: In function 'void WTF::initializeCompilationThreads()':
/amiga/odyssey/OdysseyWebBrowser/Source/WTF/wtf/CompilationThread.cpp:40:17: error: 'once_flag' in namespace 'std' does not name a type
     static std::once_flag initializeCompilationThreadsOnceFlag;
                 ^
/amiga/odyssey/OdysseyWebBrowser/Source/WTF/wtf/CompilationThread.cpp:41:5: error: 'call_once' is not a member of 'std'
     std::call_once(initializeCompilationThreadsOnceFlag, []{
     ^
/amiga/odyssey/OdysseyWebBrowser/Source/WTF/wtf/CompilationThread.cpp:41:20: error: 'initializeCompilationThreadsOnceFlag' was not declared in this scope
     std::call_once(initializeCompilationThreadsOnceFlag, []{
                    ^
Source/WTF/wtf/CMakeFiles/WTF.dir/build.make:134: recipe for target 'Source/WTF/wtf/CMakeFiles/WTF.dir/CompilationThread.cpp.obj' failed
make[3]: *** [Source/WTF/wtf/CMakeFiles/WTF.dir/CompilationThread.cpp.obj] Error 1
CMakeFiles/Makefile2:130: recipe for target 'Source/WTF/wtf/CMakeFiles/WTF.dir/all' failed
make[2]: *** [Source/WTF/wtf/CMakeFiles/WTF.dir/all] Error 2
CMakeFiles/Makefile2:559: recipe for target 'Tools/OdysseyWebBrowser/CMakeFiles/owb.dir/rule' failed
make[1]: *** [Tools/OdysseyWebBrowser/CMakeFiles/owb.dir/rule] Error 2
Makefile:288: recipe for target 'owb' failed
make: *** [owb] Error 2
```

I checked aros diff from above post, and there seems not many code related to support of pthreads in c++11.

Sebastian, what you think, is it possible to add it to our gcc in the same manner as deadwood do for aros in that diff ?

**Comment by kas1e** [comment] 2016-01-20 06:14
Some small addon from deadwood:

The C++11 thread support is there is GCC - there is nothing to implement really. You just need to make GCC correctly detect that you have pthread available or force it to think you have it. If you do, some configuration switches will  turn on and you will have the support. I think for AROS, I just forced it to think pthread is available.

**Comment by sba1** [comment] 2016-01-20 12:39
If you like, you could try it out by adding the appropriate ```--enable-threads=posix``` line to the gcc configure line. Originally, I wanted to write an own thread emulation layer but if posix works it would be much easier for the moment.

**Comment by sba1** [comment] 2016-01-25 19:18
The current procedure is to add this flag manually when configuring. You also need a special linker script that changes the constructor calling order such that the libpthread.a one is called for. For this purpose, use a dedicated linker script (e.g., https://github.com/sba1/adtools/blob/master/tests/test-thread-ldscript) until the link lib is fixed.

**Comment by Hypexed** [comment] 2017-07-11 12:25
I've come across this pthread issue my self in configure scripts. Usually a failure with discovering posix thread support. But one solution is to use change it too -lpthread instead and then it passed. It worked in my case when cross compiling. Don't know about on OS4.

**Comment by ksdhans** [comment] 2018-02-03 20:14
Any progress on this issue? Does the latest build allow you to use std::thread out-of-the-box (i.e., no messing with changing scripts, etc.)?

Being able to use std::thread would make both porting and writing code easier (especially if you're working on multi-platform stuff).

**Comment by sba1** [comment] 2018-02-04 19:35
Not yet, especially not with shared objects.

**Comment by ksdhans** [comment] 2018-02-06 06:19
> Not yet, especially not with shared objects.
Pity. Any technical barriers in the way? 

Is there any way to get this done quickly? I'd be fine with static linking only, so long as I can use the thread class.

**Comment by kas1e** [comment] 2018-02-06 12:59
@sba1 
Shared objects can wait for sure, if pure statical linkng will works, its good enough for meanwhile, just set it by default, and all can go from there :)

**Comment by sba1** [comment] 2018-02-07 20:06
The problem is that a compiler that is configured with a thread model will generate bad shared objects (bad in a sense that the ABI may change in the future). I'm not sure if there is a solution to switch the thread model at other than to provide two builds.

**Comment by ksdhans** [comment] 2018-02-08 00:57
You mean that all shared objects are incompatible with previous versions? Or, that the generated C++ stdlib is incompatible? 

Microsoft's Visual C++ has provided multiple C++ libs for years, including ones with and without multithreading ability. I'd be fine with having multiple stdlibs for with and without threading, so long as the correct one is loaded automatically at runtime. Or, I'd use static linking...

Most important is to be able to use key C++11 features in the first place.

**Comment by sba1** [comment] 2018-05-07 17:42
I started with the thread support some days ago. The gcc comes with an own abstraction layer that is a subset of the pthreads API. In my implementation, it will be possible to link against different target implementations, so it can be decided at link time, which thread implementation should be used. So far, I implemented the single thread mode (which behaves as before, i.e., no threads are supported) and a native AmigaOs one. The latter one uses AmigaOS interfaces directly and it is not completely finished yet. The object file is called ```gthr-amigaos-native.o```. There will also be a pthread wrapper, for those who require full pthread compatibility.

The patch is developed in the gcc 8 patch queue. You may try it if you like.

**Comment by ksdhans** [comment] 2018-05-08 07:52
Great to see progress. I'm pretty busy with other stuff right now, so I'm not sure when I'll get round to trying it out. Hopefully soonish.

**Comment by sba1** [comment] 2018-05-10 06:09
It is now possible to choose the actual thread implementation via the ```-athread``` option. Possible choices are ```single```, ```native```, and ```pthread```. Still gcc 8 only, but once it is finished, i'll backport it to gcc 6.

Note that ```native``` is an own implementation and thus probably contains bugs. And ```pthread``` is not provided yet.

**Comment by sba1** [comment] 2018-05-20 04:41
The feature is more complete now (but still unfinished in some aspects). But initial work has been done, hence I close this issue. Please file new issues if you find something working weird.

**Closed by sba1** 2018-05-20 04:41 UTC
