### ISSUE TITLE
Simple std::this_thread::get_id() crashes with -athread=native

### ISSUE THREAD

**Issue by kas1e** [sba1/adtools#76] opened 2019-10-20 18:45 UTC
@Sebastian

Found today that this simple test case crashes on latest build of adtools, with newlib and with clib2:

```
#include <stdio.h>
#include <string>
#include <thread>

int main()
{
	printf("before\n");
	std::thread::id id = std::this_thread::get_id();
	printf("after\n");
}
```

Build it as ```g++ -athread=native test.cpp -o test```. I have words "before" in output, and then crash on get_id() call. 

I of course test if it works on win32 and linux , and it works for them of course, so its amigaos4 crash only.

There is crashlog:

```
Stack trace:
    native kernel module kernel+0x0002d8b4
    native kernel module kernel+0x0002d8b4
    test:_ZNSt11this_thread6get_idEv()+0x48 (section 1 @ 0x1C04)
    test:main()+0x24 (section 1 @ 0x1B54)
    native kernel module newlib.library.kmod+0x00002580
    native kernel module newlib.library.kmod+0x00003298
    native kernel module newlib.library.kmod+0x000037cc
    test:_start()+0x170 (section 1 @ 0x1AB8)
    native kernel module dos.library.kmod+0x0002a5d8
    native kernel module kernel+0x0006b590
    native kernel module kernel+0x0006b5d8

PPC disassembly:
 0182d8ac: 83aa0114   lwz               r29,276(r10)
 0182d8b0: 4e800421   bctrl             
*0182d8b4: a13e002c   lhz               r9,44(r30)
 0182d8b8: 7d2a0734   extsh             r10,r9
 0182d8bc: 39290001   addi              r9,r9,1
```

Is there any hope for fast-fix, or at least can it be somehow workarounded so to make it works ? 

Thanks !

**Comment by kas1e** [comment] 2019-10-20 18:49
And that exactly get_id() which crashes , as for example that test case works as expected:

```
#include <stdio.h>
#include <string>
#include <thread>
#include <chrono>


int main()
{
	printf("before\n");
	std::this_thread::sleep_for(std::chrono::seconds(1));
	printf("after\n");
}
```

I.e. whole threading works, "this_thread" works too, just get_id() in native threading support crashes.

**Comment by kas1e** [comment] 2019-10-20 19:23
Same crash happens even if i use clib2's threadsafe version.

**Comment by salass00** [comment] 2021-01-04 10:55
Looking at the code in gthr-amigaos-native.c the problem is that init_threadstore() has not been called yet so when __gthread_self() tries to obtain the semaphore &threadstore->sem it leads to a NULL pointer access.

A quick fix would probably be to add the line:
__gthread_once (&threadstore_once, init_threadstore);

in __gthread_self() just after:
__gthread_once (&libs_once, init_libs);

Same as how it is done in the __gthread_create() function.

**Comment by sba1** [comment] 2021-01-04 11:04
If possible, please submit a merge request that contain the fix. I have zero time these days. Alternatively, people must link against the fixed version on their own.

**Comment by salass00** [comment] 2021-01-04 13:07
Typing "bin/gild genpatch gcc 8" as written in the readme results in the error message:
Specified branch '8' does not match checked out branch 'b'8''
Any idea what I am doing wrong?

I've already done the commands:
git submodule init
git submodule update
bin/gild clone
bin/gild checkout binutils 2.23.2
bin/gild checkout gcc 8

**Comment by salass00** [comment] 2021-01-04 16:03
Pull request created: https://github.com/sba1/adtools/pull/89

**Comment by sba1** [comment] 2021-01-04 16:09
Merged thanks!

**Closed by sba1** 2021-01-04 16:09 UTC
