### ISSUE TITLE
Fix C99 flags so C++11 methods can be used.

### ISSUE THREAD

**Issue by AV00** [sba1/adtools#19] opened 2017-02-09 10:47 UTC
Currently in c++config.h (I guess created by configure script) _GLIBCXX_USE_C99 is undefined.
This in turn prevents C++11 methods such as std::to_string() to work (they're undefined too), so to do such string manipulation you either have to use the c-library or string streams.

Thanks.

**Comment by sba1** [comment] 2017-02-10 21:33
I'm not sure if clib2 or newlib are really full C99 libraries. Please have a look at this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58393

If I understood it correctly, then it means that in GCC 6 the requirements were a bit relaxed.

I see three possibilities:

1. We use GCC 6 (this still has issues) and hope that the support will be automatically enabled. Indeed I plan to have concurrent releases of adtools gcc packaged.

2. We enforce the definition of that macro and hope for the best

3. We relax the requirements in GCC 5 and allow in particular when clib or newlib is used or use we try the patch that have been added to the bug.

**Comment by AV00** [comment] 2017-02-11 11:35
Hi.

Let's go in order:

> I'm not sure if clib2 or
newlib are really full C99 libraries.

Well, this ought to be
interest of their respective maintainers. Though I would be surprised they
wouldn't. If I were to investigate why they're not detected to be fully
C99, where would you suggest I look ? I suppose it's somewhere in the
configure script, but which is it ? Could you just point out where it is
in the project tree ?

> I see three possibilities:
>

>     We use GCC 6 (this still has issues)
and hope that the support will be automatically enabled. Indeed I plan to
have concurrent releases of adtools gcc packaged.

Hum... what
issues does 6 have ? I guess we need working pthreads and atomic stuff
?
I read the bugreport, it seems that in 6 is fixed for uClib.

> 
>     We enforce the definition
of that macro and hope for the best

Tried this one with 5, and
it didn't work: I didn't look to closely (but if you like, I can have a
closer look), but I think there was a problem with the namespace: the
methods (which are just sXprintf family) are there, but not defined in
'std::'.

>     We relax the requirements
in GCC 5 and allow in particular when clib or newlib is used or use we try
the patch that have been added to the bug.

Also a good idea.

I'm open to suggestions, I have a bit of spare time so tell me
into which direction to look.

(I'm replying via email because
the web interface says "You can't comment at this time." Weird)

**Comment by sba1** [comment] 2017-03-04 06:48
I made few changes. You still have to undef __STRICT_ANSI__ when compiling files. For instance, ```-std=c++11 -U__STRICT_ANSI__```.

**Comment by AV00** [comment] 2017-03-07 11:38
Ok, I've tried and the newest patch works with newlib, not clib2. Which is an improvement of course. I see you also forced the undefinition of STRICT_ANSI in the header.

In the comments you wrote that you're waiting for newlib to be fixed. Shall we keep the issue open in the meantime ? Or close it ?

**Comment by sba1** [comment] 2017-03-07 19:58
> Which is an improvement of course. I see you also forced the undefinition of STRICT_ANSI in the header.

Yes, unfortunately this seems to be necessary with current newlib SDK (the includes don't know about C99).

> In the comments you wrote that you're waiting for newlib to be fixed. Shall we keep the issue open in the meantime ? Or close it ?

I would like to keep this open as long as the clib2 variant does suffer from the same problem. Best would be to address this issue within clib2 directly if possible,

**Comment by AV00** [comment] 2017-03-07 20:05
> I would like to keep this open as long as the clib2 variant does suffer from the same problem. Best would be to address this issue within clib2 directly if possible,

Yes, agreed. The same could be said for newlib.
Having to undefine that flag feels... wrong.

**Comment by sba1** [comment] 2018-05-23 08:17
I think that the problem is mostly fixed with gcc 8. Missing features are more a problem of the respective clibs.

**Closed by sba1** 2018-05-23 08:17 UTC

**Comment by AV00** [comment] 2018-05-31 11:47
On mercoledì 23 maggio 2018 01:17:58 CEST Sebastian Bauer wrote:
> I think that the problem is mostly fixed with gcc 8. Missing features are
> more a problem of the respective clibs.

Speaking of which, I see you updated the native archives but there's (sofar) 
no Debian cross compiler package for 8.

Do you plan to release it ?

Thanks.

-- 
Bye, A.

**Comment by sba1** [comment] 2018-05-31 18:30
Am 2018-05-31 13:47, schrieb AV00:
> Speaking of which, I see you updated the native archives but there's
> (sofar)
> no Debian cross compiler package for 8.
> Do you plan to release it ?

Currently, the problem is that we need a custom clib2 build. That makes 
it more difficult to package it, because the clib2 of the SDK cannot be 
used.

Bye
Sebastian

**Comment by sba1** [comment] 2018-06-01 17:47
Am 2018-06-01 11:22, schrieb AV00:
> Idea:
> - change the installation script for the SDK so it DOESN'T extract the
> CLIB2
> archive from the SDK (but only the other files).
> - create a debian package for the fixed CLIB2.
> - make such package a requirement for the SDK package
> 
> Sounds good ?

Yes, that would be a way. Another one would be to bundle the files 
directly with the sdk package. This should be a bit easier to achieve. 
However, building-wise, the compiling process depends on the SDK but one 
needs a compiler to build the latest clib2. This makes it a bit more 
complicated (though still no rocket since ;) ), especially as the Travis 
build is already nearly at the limit.

Bye
Sebastian

**Comment by AV00** [comment] 2018-06-04 10:30
On venerdì 1 giugno 2018 17:47:31 CEST Sebastian Bauer wrote:

> > Sounds good ?
> 
> Yes, that would be a way. Another one would be to bundle the files
> directly with the sdk package. This should be a bit easier to achieve.
> However, building-wise, the compiling process depends on the SDK but one
> needs a compiler to build the latest clib2. This makes it a bit more
> complicated (though still no rocket since ;) ), especially as the Travis
> build is already nearly at the limit.

Should I open an appropriate ticket to track this one ? 

> 
> Bye
> Sebastian


-- 
Bye, A.

**Comment by sba1** [comment] 2018-06-04 10:53
Am 2018-06-04 12:30, schrieb AV00:
>> However, building-wise, the compiling process depends on the SDK but
> one
>> needs a compiler to build the latest clib2. This makes it a bit more
>> complicated (though still no rocket since ;) ), especially as the
> Travis
>> build is already nearly at the limit.

> Should I open an appropriate ticket to track this one ?

Yes, please go ahead :)

Bye
Sebastian
